### ISSUE TITLE
Following up on an email...

### ISSUE THREAD

**Issue by amchagas** [neurogears/neurogears.github.io#15]
HI @glopesdev!

Sorry for sending this as an issue, but a couple of weeks ago I sent an email to the neurogears mailbox asking about doing a workshop at Sussex Neuroscience and asking about potential ways of interacting/collaborating long term... Just wanted to make sure it did not go straight to spam or something! also please do let me know if there is a better email address/or other communication tool you'd rather use!

**Comment by glopesdev** [comment]
@amchagas Thank you for reaching out, and no worries this approach is totally valid! Indeed the last month was so frenetic in terms of email activity that your contact somehow slipped through the cracks. I will follow up on your original message, thanks.

**Comment by amchagas** [comment]
Hi, me again giving a little nudge about another email... :P
